//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManager.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public Task()
        {
            this.Workers = new HashSet<User>();
            this.Comments = new HashSet<Comment>();
        }
    
        public int Id { get; set; }
        public string Content { get; set; }
        public Nullable<int> Percentage { get; set; }
        public Nullable<bool> IsDone { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> TeamId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<User> Workers { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual Team Team { get; set; }
    }
}
