//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskOperator.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public Task()
        {
            this.Attachment = new HashSet<Attachment>();
        }
    
        public int Id { get; set; }
        public int Percentage { get; set; }
        public string Content { get; set; }
        public System.DateTime Date { get; set; }
        public string Name { get; set; }
        public byte State { get; set; }
        public Nullable<int> WorkerId { get; set; }
    
        public virtual ICollection<Attachment> Attachment { get; set; }
        public virtual User Worker { get; set; }
    }
}
