//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomToDoManager.UserService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ToDoItem", Namespace="http://schemas.datacontract.org/2004/07/ToDoManagerService.Entities")]
    [System.SerializableAttribute()]
    public partial class ToDoItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsCompletedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ToDoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsCompleted {
            get {
                return this.IsCompletedField;
            }
            set {
                if ((this.IsCompletedField.Equals(value) != true)) {
                    this.IsCompletedField = value;
                    this.RaisePropertyChanged("IsCompleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ToDoId {
            get {
                return this.ToDoIdField;
            }
            set {
                if ((this.ToDoIdField.Equals(value) != true)) {
                    this.ToDoIdField = value;
                    this.RaisePropertyChanged("ToDoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserService.IToDoManager")]
    public interface IToDoManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IToDoManager/GetTodoList", ReplyAction="http://tempuri.org/IToDoManager/GetTodoListResponse")]
        CustomToDoManager.UserService.ToDoItem[] GetTodoList(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IToDoManager/GetTodoList", ReplyAction="http://tempuri.org/IToDoManager/GetTodoListResponse")]
        System.Threading.Tasks.Task<CustomToDoManager.UserService.ToDoItem[]> GetTodoListAsync(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IToDoManager/UpdateToDoItem", ReplyAction="http://tempuri.org/IToDoManager/UpdateToDoItemResponse")]
        void UpdateToDoItem(CustomToDoManager.UserService.ToDoItem todo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IToDoManager/UpdateToDoItem", ReplyAction="http://tempuri.org/IToDoManager/UpdateToDoItemResponse")]
        System.Threading.Tasks.Task UpdateToDoItemAsync(CustomToDoManager.UserService.ToDoItem todo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IToDoManager/CreateToDoItem", ReplyAction="http://tempuri.org/IToDoManager/CreateToDoItemResponse")]
        void CreateToDoItem(CustomToDoManager.UserService.ToDoItem todo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IToDoManager/CreateToDoItem", ReplyAction="http://tempuri.org/IToDoManager/CreateToDoItemResponse")]
        System.Threading.Tasks.Task CreateToDoItemAsync(CustomToDoManager.UserService.ToDoItem todo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IToDoManager/DeleteToDoItem", ReplyAction="http://tempuri.org/IToDoManager/DeleteToDoItemResponse")]
        void DeleteToDoItem(int todoItemId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IToDoManager/DeleteToDoItem", ReplyAction="http://tempuri.org/IToDoManager/DeleteToDoItemResponse")]
        System.Threading.Tasks.Task DeleteToDoItemAsync(int todoItemId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IToDoManager/CreateUser", ReplyAction="http://tempuri.org/IToDoManager/CreateUserResponse")]
        int CreateUser(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IToDoManager/CreateUser", ReplyAction="http://tempuri.org/IToDoManager/CreateUserResponse")]
        System.Threading.Tasks.Task<int> CreateUserAsync(string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IToDoManagerChannel : CustomToDoManager.UserService.IToDoManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ToDoManagerClient : System.ServiceModel.ClientBase<CustomToDoManager.UserService.IToDoManager>, CustomToDoManager.UserService.IToDoManager {
        
        public ToDoManagerClient() {
        }
        
        public ToDoManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ToDoManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ToDoManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ToDoManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CustomToDoManager.UserService.ToDoItem[] GetTodoList(int userId) {
            return base.Channel.GetTodoList(userId);
        }
        
        public System.Threading.Tasks.Task<CustomToDoManager.UserService.ToDoItem[]> GetTodoListAsync(int userId) {
            return base.Channel.GetTodoListAsync(userId);
        }
        
        public void UpdateToDoItem(CustomToDoManager.UserService.ToDoItem todo) {
            base.Channel.UpdateToDoItem(todo);
        }
        
        public System.Threading.Tasks.Task UpdateToDoItemAsync(CustomToDoManager.UserService.ToDoItem todo) {
            return base.Channel.UpdateToDoItemAsync(todo);
        }
        
        public void CreateToDoItem(CustomToDoManager.UserService.ToDoItem todo) {
            base.Channel.CreateToDoItem(todo);
        }
        
        public System.Threading.Tasks.Task CreateToDoItemAsync(CustomToDoManager.UserService.ToDoItem todo) {
            return base.Channel.CreateToDoItemAsync(todo);
        }
        
        public void DeleteToDoItem(int todoItemId) {
            base.Channel.DeleteToDoItem(todoItemId);
        }
        
        public System.Threading.Tasks.Task DeleteToDoItemAsync(int todoItemId) {
            return base.Channel.DeleteToDoItemAsync(todoItemId);
        }
        
        public int CreateUser(string name) {
            return base.Channel.CreateUser(name);
        }
        
        public System.Threading.Tasks.Task<int> CreateUserAsync(string name) {
            return base.Channel.CreateUserAsync(name);
        }
    }
}
